/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import datos.Ciudad;
import datos.Viaje;

import java.awt.Color;
import java.awt.Rectangle;

import javax.swing.JOptionPane;
import grafo.Grafo;
import grafo.GrafoD;

/**
 *
 * @author david
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    private Grafo<Ciudad, Viaje> grafo = new GrafoD<>();
    private int n = 0;
     int nodo1X = -1;
     int nodo1Y = -1;
     int nodo2X = -1;
     int nodo2Y = -1;
     String nnodo1;
     String nnodo2;
     boolean mov;
     int disX = 0;
     int disY = 0;
     Rectangle rectangulo = new Rectangle(30, 30);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        if (evt.getButton() == 1){
            boolean haynodo = false;
            for (int i = 0; i < grafo.orden(); i++) {
                rectangulo.x = grafo.getVertice(i).cordX;
                rectangulo.y = grafo.getVertice(i).cordY;
                if(rectangulo.contains(evt.getX(), evt.getY())){
                    Lienzo.clickSobreNodo(jPanel2.getGraphics(), grafo.getVertice(i).cordX, grafo.getVertice(i).cordY, Color.green, grafo.getVertice(i).dato.getNombre());
                    haynodo = true;
                    n++;
                    if (nodo1X == -1 && nodo1Y == -1){
                        nodo1X = grafo.getVertice(i).cordX;
                        nodo1Y = grafo.getVertice(i).cordY;
                        nnodo1 = grafo.getVertice(i).dato.getNombre();
                    }else{
                        nodo2X = grafo.getVertice(i).cordX;
                        nodo2Y = grafo.getVertice(i).cordY;
                        nnodo2 = grafo.getVertice(i).dato.getNombre();
                    }
                }
            }
            if (!haynodo){
                String nombre = JOptionPane.showInputDialog("Nombre de la ciudad: ");
                String pais = JOptionPane.showInputDialog("Nombre del pais: ");
                grafo.addVertice(new Ciudad(nombre, pais), evt.getX(), evt.getY());
                Lienzo.pintarCirculo(jPanel2.getGraphics(), nombre, evt.getX(), evt.getY());
            }
            if (n == 2){
                int tam = Integer.parseInt(JOptionPane.showInputDialog("Costo: "));
                Lienzo.pintarFlecha(jPanel2.getGraphics(), nodo1X, nodo1Y, nodo2X, nodo2Y, tam);
                Lienzo.pintarCirculo(jPanel2.getGraphics(), nnodo1, nodo1X, nodo1Y);
                Lienzo.pintarCirculo(jPanel2.getGraphics(), nnodo2, nodo2X, nodo2Y);
                
                nodo1X = -1;
                nodo1Y = -1;
                nodo2X = -1;
                nodo2Y = -1;
                nnodo1 = "";
                nnodo2 = "";
                n = 0;
                
            }
        }
        if (evt.getButton() == 2) {
        }
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   
}
