/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Maria Jose Amezquita
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrame = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        SideLabel = new javax.swing.JPanel();
        TopBarLabel = new javax.swing.JPanel();
        ExitButton = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        graphMap1 = new gui.GraphMap();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("proyecto-grafos");
        setBackground(new java.awt.Color(17, 17, 26));
        setLocationByPlatform(true);
        setName("MainFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.POPUP);

        MainFrame.setBackground(new java.awt.Color(0, 51, 51));
        MainFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MainFrame.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        SideLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout SideLabelLayout = new javax.swing.GroupLayout(SideLabel);
        SideLabel.setLayout(SideLabelLayout);
        SideLabelLayout.setHorizontalGroup(
            SideLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        SideLabelLayout.setVerticalGroup(
            SideLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        MainFrame.add(SideLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 570));

        TopBarLabel.setBackground(new java.awt.Color(255, 255, 255));
        TopBarLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TopBarLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopBarLabelMouseDragged(evt);
            }
        });
        TopBarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TopBarLabelMousePressed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(0, 0, 0));
        ExitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitButton.setText("x");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });

        TitleLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        TitleLabel.setText("Mapa");

        javax.swing.GroupLayout TopBarLabelLayout = new javax.swing.GroupLayout(TopBarLabel);
        TopBarLabel.setLayout(TopBarLabelLayout);
        TopBarLabelLayout.setHorizontalGroup(
            TopBarLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarLabelLayout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(TitleLabel)
                .addGap(324, 324, 324)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        TopBarLabelLayout.setVerticalGroup(
            TopBarLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLabelLayout.createSequentialGroup()
                .addGroup(TopBarLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(TitleLabel))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        MainFrame.add(TopBarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        javax.swing.GroupLayout graphMap1Layout = new javax.swing.GroupLayout(graphMap1);
        graphMap1.setLayout(graphMap1Layout);
        graphMap1Layout.setHorizontalGroup(
            graphMap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        graphMap1Layout.setVerticalGroup(
            graphMap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        MainFrame.add(graphMap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 660, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        System.exit(0);  
    }//GEN-LAST:event_ExitButtonMouseClicked
    
    private int x, y;
    
    private void TopBarLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopBarLabelMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_TopBarLabelMousePressed

    private void TopBarLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopBarLabelMouseDragged
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_TopBarLabelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitButton;
    private javax.swing.JPanel MainFrame;
    private javax.swing.JPanel SideLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel TopBarLabel;
    private java.awt.Canvas canvas1;
    private gui.GraphMap graphMap1;
    // End of variables declaration//GEN-END:variables
}
